fn main() {}

macro_rules! test {}
//~^ ERROR unexpected end of macro invocation
